name: Test Run GetManager
on:
  workflow_dispatch: # 手动点击运行

jobs:
  run_get:
    runs-on: ubuntu-latest
    # uses必须和runson同级，缩进2空格
    uses: ./.github/workflows/get-manager.yml
    with:
      kernelsu_variant: ReSukiSU
      ksu_branch: Stable(标准)
