name: Test Run GetManager
on:
  workflow_dispatch:

jobs:
  run_get:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/get-manager.yml
    with:
      kernelsu_variant: ReSukiSU
      ksu_branch: Stable(标准)
